version: "2"
services:
  iot_door:
    build: .
    image: iot_door:0.2
    volumes:
      - ~/workspace/IOT-Hotel-Room-Protection:/usr/iot_door
    restart: always
    privileged: true
    networks:
      myvlan:
          ipv4_address: 10.10.10.15
  db:
    image: apcheamitru/arm32v7-mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: example
    restart: always
    privileged: true
    networks:
      myvlan:
          ipv4_address: 10.10.10.16
    
networks:
  myvlan:
    driver: macvlan
    driver_opts:
      parent: wlan0
    ipam:
      config:
        - subnet: 10.10.10.0/24
