FROM ubuntu:bionic

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

COPY Pipfile .
COPY Pipfile.lock .

RUN apt-get update &&\
    apt-get -y install python3 &&\
    apt-get -y install python3-pip &&\
    pip3 install pipenv &&\
    pipenv --python /usr/bin/python3 install --deploy --system

EXPOSE 5001

CMD ["python3","/repo/dashboard_in_python/controller.py"]