FROM ubuntu:bionic

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

COPY . /usr/iot

WORKDIR /usr/iot

RUN \
    apt-get update && apt-get -y install python3-pip &&\
    pip3 install pipenv && pipenv install --system --deploy

EXPOSE 5000

CMD ["python3","portal/controller.py"]